/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "msg_constants.h"

namespace msgtype {

const msgConstants g_msg_constants;

msgConstants::msgConstants() {
}

} // namespace

