/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef msg_CONSTANTS_H
#define msg_CONSTANTS_H

#include "msg_types.h"

namespace msgtype {

class msgConstants {
 public:
  msgConstants();

};

extern const msgConstants g_msg_constants;

} // namespace

#endif
