/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ff
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RegisterToBrokerReq : TBase
  {
    private int _node_type;
    private string _service_name;

    public int Node_type
    {
      get
      {
        return _node_type;
      }
      set
      {
        __isset.node_type = true;
        this._node_type = value;
      }
    }

    public string Service_name
    {
      get
      {
        return _service_name;
      }
      set
      {
        __isset.service_name = true;
        this._service_name = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool node_type;
      public bool service_name;
    }

    public RegisterToBrokerReq() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Node_type = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Service_name = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RegisterToBrokerReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.node_type) {
        field.Name = "node_type";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Node_type);
        oprot.WriteFieldEnd();
      }
      if (Service_name != null && __isset.service_name) {
        field.Name = "service_name";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Service_name);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RegisterToBrokerReq(");
      sb.Append("Node_type: ");
      sb.Append(Node_type);
      sb.Append(",Service_name: ");
      sb.Append(Service_name);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
