/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class WorkerCallMsgReq : TBase
{
  private short _cmd;
  private byte[] _body;

  public short Cmd
  {
    get
    {
      return _cmd;
    }
    set
    {
      __isset.cmd = true;
      this._cmd = value;
    }
  }

  public byte[] Body
  {
    get
    {
      return _body;
    }
    set
    {
      __isset.body = true;
      this._body = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool cmd;
    public bool body;
  }

  public WorkerCallMsgReq() {
    this._cmd = 0;
    this.__isset.cmd = true;
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.I16) {
            Cmd = iprot.ReadI16();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            Body = iprot.ReadBinary();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("WorkerCallMsgReq");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.cmd) {
      field.Name = "cmd";
      field.Type = TType.I16;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI16(Cmd);
      oprot.WriteFieldEnd();
    }
    if (Body != null && __isset.body) {
      field.Name = "body";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteBinary(Body);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("WorkerCallMsgReq(");
    sb.Append("Cmd: ");
    sb.Append(Cmd);
    sb.Append(",Body: ");
    sb.Append(Body);
    sb.Append(")");
    return sb.ToString();
  }

}

