/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ffrpc_msg_CONSTANTS_H
#define ffrpc_msg_CONSTANTS_H

#include "ffrpc_msg_types.h"

namespace ffrpc_msg {

class ffrpc_msgConstants {
 public:
  ffrpc_msgConstants();

};

extern const ffrpc_msgConstants g_ffrpc_msg_constants;

} // namespace

#endif
