/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ffrpc_msg_constants.h"

namespace ff {

const ffrpc_msgConstants g_ffrpc_msg_constants;

ffrpc_msgConstants::ffrpc_msgConstants() {
}

} // namespace

